# Generated by Django 3.0.4 on 2020-05-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temphum', '0002_temphum_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='temphum',
            name='land',
            field=models.CharField(default='Sin terreno', max_length=20, verbose_name='Terreno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temphum',
            name='latitude',
            field=models.IntegerField(default=0, verbose_name='Latitud'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='temphum',
            name='length',
            field=models.IntegerField(default=0, verbose_name='Longitud'),
            preserve_default=False,
        ),
    ]
